### ISSUE TITLE
Port to CoinMarketCap API Pro

### ISSUE THREAD

**Issue by JasonG-FR** [JasonG-FR/pyCoin#3]
Switch to CMC API Pro before December 2018

**Comment by tmlee** [comment]
@JasonG-FR might want to consider our open public API at https://www.coingecko.com/api

Happy to answer any questions and feedback you may have

**Comment by JasonG-FR** [comment]
Thanks for the suggestion, I successfully implemented CoinGecko in a branch 2 years ago, but I apparently forgot to merge it.

It's now done with commit https://github.com/JasonG-FR/pyCoin/commit/9bf12f4ce98bd771f33903f58184821abf41baec.
